apiVersion: 0.0.1
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: tf-job
    registry: kubeflow
name: rl-app
registries:
  incubator:
    gitVersion:
      commitSha: ea3408d44c2d8ea4d321364e5533d5c60e74bce0
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
